version: '3.7'

services:
  api-docs:
    restart: always
    image: whatwewant/yapi:${SERVICE_API_DOCS_IMAGE_VERSION}
    # ports:
    #   - 0.0.0.0:8080:8080
    environment:
      ROOT_URL: ${SERVICE_API_DOCS_ROOT_URL}
      ADMIN_EMAIL: ${SERVICE_API_DOCS_ADMIN_EMAIL}
      DB_ENGINE: ${SERVICE_API_DOCS_DB_ENGINE}
      DB_HOST: ${SERVICE_API_DOCS_DB_HOST}
      DB_PORT: ${SERVICE_API_DOCS_DB_PORT}
      DB_USER: ${SERVICE_API_DOCS_DB_USER}
      DB_PASS: ${SERVICE_API_DOCS_DB_PASS}
      DB_NAME: ${SERVICE_API_DOCS_DB_NAME}
      MAIL_ENABLE: enable
      MAIL_HOST: ${SERVICE_API_DOCS_MAIL_HOST}
      MAIL_PORT: ${SERVICE_API_DOCS_MAIL_PORT}
      MAIL_FROM: ${SERVICE_API_DOCS_MAIL_USER}
      MAIL_USER: ${SERVICE_API_DOCS_MAIL_USER}
      MAIL_PASS: ${SERVICE_API_DOCS_MAIL_PASS}
      DOREAMON_ONLY: ${SERVICE_API_DOCS_DOREAMON_ONLY}
      DOREAMON_CLIENT_ID: ${SERVICE_API_DOCS_DOREAMON_CLIENT_ID}
      DOREAMON_CLIENT_SECRET: ${SERVICE_API_DOCS_SERVICE_API_DOCS_DOREAMON_CLIENT_SECRET}
      
networks:
  default:
    external: true
    name: compose-ingress
